import type { BacktestData } from './types.js';

/**
 * Default backtest dataset bundled with the CLI.
 * Contains 10 threads from Bitcoin, Ethereum, Solana, and Dogecoin.
 */
export const DEFAULT_BACKTEST_DATA: BacktestData = {
  metadata: {
    id: 'default',
    name: 'Default Backtest Dataset',
    created_at: '2026-02-26T00:00:00Z',
  },
  threads: [
    {
      project_id: 'ethereum',
      project_name: 'Ethereum',
      project_symbol: '$ETH',
      project_categories: [
        'smart-contract-platform',
        'layer-1',
        'ethereum-ecosystem',
        'proof-of-stake-pos',
        'world-liberty-financial-portfolio',
      ],
      project_description:
        'Ethereum is a global, open-source platform for decentralized applications.',
      text: 'Balaji Srinivasan describes a "Global Privacy Era" as crypto\'s third phase, where the next decade of Web3 focuses on protecting user data and financial sovereignty through strong encryption rather than scalability or speed. Ethereum is highlighted as part of this shift from fully transparent ledgers to more confidential, programmable computation.',
      timestamp: '2025-12-31T20:00:00Z',
      price_on_fetch: 2969.01,
      price_on_eval: 2971.55,
      citations: [{ title: '2006719380713869499' }, { title: '2006683920881037680' }],
    },
    {
      project_id: 'solana',
      project_name: 'Solana',
      project_symbol: '$SOL',
      project_categories: [
        'smart-contract-platform',
        'solana-ecosystem',
        'layer-1',
        'alleged-sec-securities',
        'proof-of-stake-pos',
        'made-in-usa',
        'coinlist-launchpad',
      ],
      project_description:
        'Solana is a high-performance Layer 1 blockchain designed for mass adoption by providing a fast, secure, and low-cost environment for decentralized applications.',
      text: 'ORE partners with PrivacyCash to launch an official shielded pool on Solana, enabling live private transfers of ORE as a native store-of-value token. Builders also announce Pandora OS v2.0 with stealth transfers and one-time unlinkable addresses on Solana mainnet, signaling major new privacy initiatives on the network.',
      timestamp: '2026-01-01T01:00:00Z',
      price_on_fetch: 124.98,
      price_on_eval: 124.94,
      citations: [{ title: '2006787547519918102' }, { title: '2006787600028410119' }],
    },
    {
      project_id: 'solana',
      project_name: 'Solana',
      project_symbol: '$SOL',
      project_categories: [
        'smart-contract-platform',
        'solana-ecosystem',
        'layer-1',
        'alleged-sec-securities',
        'proof-of-stake-pos',
        'made-in-usa',
        'coinlist-launchpad',
      ],
      project_description:
        'Solana is a high-performance Layer 1 blockchain designed for mass adoption by providing a fast, secure, and low-cost environment for decentralized applications.',
      text: 'Solana is introducing the c-spl confidential token standard in Q1 2026, enabling encrypted balances and native private transfers. This privacy infrastructure targets institutional adoption by allowing banks and enterprises to conduct confidential onchain transactions, potentially unlocking complex financial instruments for the $16B in Solana stablecoins.',
      timestamp: '2026-01-01T06:00:00Z',
      price_on_fetch: 125.06,
      price_on_eval: 124.43,
      citations: [{ title: '2006857900543848485' }, { title: '2006862849327435958' }],
    },
    {
      project_id: 'bitcoin',
      project_name: 'Bitcoin',
      project_symbol: '$BTC',
      project_categories: [
        'smart-contract-platform',
        'layer-1',
        'proof-of-work-pow',
        'bitcoin-ecosystem',
      ],
      project_description:
        "Bitcoin is the world's first decentralized cryptocurrency, created in 2009 by the pseudonymous Satoshi Nakamoto.",
      text: 'BlackRock transferred 1,134 BTC (~$101.4M) and 7,255 ETH (~$22.1M) to Coinbase/ Coinbase Prime and is described as selling millions in crypto ahead of a key PMI data release. The move coincides with $2.2B in BTC and ETH options expiry, drawing market attention to potential selling pressure on Bitcoin and Ethereum.',
      timestamp: '2026-01-01T19:00:00Z',
      price_on_fetch: 88053,
      price_on_eval: 88266,
      citations: [{ title: '2007064336708354389' }, { title: '2007066963671924967' }],
    },
    {
      project_id: 'solana',
      project_name: 'Solana',
      project_symbol: '$SOL',
      project_categories: [
        'smart-contract-platform',
        'solana-ecosystem',
        'layer-1',
        'alleged-sec-securities',
        'proof-of-stake-pos',
        'made-in-usa',
        'coinlist-launchpad',
      ],
      project_description:
        'Solana is a high-performance Layer 1 blockchain designed for mass adoption by providing a fast, secure, and low-cost environment for decentralized applications.',
      text: 'Tweets highlight Solana\'s active memecoin culture, with users trading and promoting tokens like $KITKAT, $wif, SolanaWhale, and Epileptic, and tools such as MemeMax and 24/7 "Solana Memecoin Hunting" communities emerging. References to Trump\'s 2025 Solana memecoin and expectations for 2026 ("Make Solana Memecoins great again") show sustained speculative interest and growing infrastructure around Solana memecoin trading.',
      timestamp: '2026-01-02T01:00:00Z',
      price_on_fetch: 126.59,
      price_on_eval: 127.47,
      citations: [{ title: '2007142205451055298' }, { title: '2007150298876522740' }],
    },
    {
      project_id: 'dogecoin',
      project_name: 'Dogecoin',
      project_symbol: '$DOGE',
      project_categories: [
        'smart-contract-platform',
        'meme-token',
        'dog-themed-coins',
        'elon-musk-inspired-coins',
        'proof-of-work-pow',
        '4chan-themed',
      ],
      project_description:
        'Dogecoin is a cryptocurrency based on the popular "Doge" Internet meme and features a Shiba Inu on its logo.',
      text: 'Tweets highlight growing focus on a proposed Bitwise Dogecoin ETF (ticker "BWOW"), emphasizing that it carries high risk, significant volatility, and potential for complete loss of investment, and is not registered under the 1940 Act. Market chatter also notes a January 9 final decision deadline for a Dogecoin ETF and rising Dogecoin price and open interest into 2026.',
      timestamp: '2026-01-02T07:00:00Z',
      price_on_fetch: 0.128493,
      price_on_eval: 0.132792,
      citations: [{ title: '2007168051129840065' }, { title: '2007118652018196634' }],
    },
    {
      project_id: 'bitcoin',
      project_name: 'Bitcoin',
      project_symbol: '$BTC',
      project_categories: [
        'smart-contract-platform',
        'layer-1',
        'proof-of-work-pow',
        'bitcoin-ecosystem',
      ],
      project_description:
        "Bitcoin is the world's first decentralized cryptocurrency, created in 2009 by the pseudonymous Satoshi Nakamoto.",
      text: 'Bitcoin users mark Proof of Keys Day, coinciding with the 17th anniversary of the Genesis Block, by urging holders to withdraw BTC from exchanges into cold storage and verify self-custody. Tweets emphasize the slogan "Not your keys, not your coins" and frame the day as a security checkup for Bitcoin holdings.',
      timestamp: '2026-01-02T15:00:00Z',
      price_on_fetch: 89551,
      price_on_eval: 90310,
      citations: [{ title: '2007362498282901908' }, { title: '2007373924133417089' }],
    },
    {
      project_id: 'solana',
      project_name: 'Solana',
      project_symbol: '$SOL',
      project_categories: [
        'smart-contract-platform',
        'solana-ecosystem',
        'layer-1',
        'alleged-sec-securities',
        'proof-of-stake-pos',
        'made-in-usa',
        'coinlist-launchpad',
      ],
      project_description:
        'Solana is a high-performance Layer 1 blockchain designed for mass adoption by providing a fast, secure, and low-cost environment for decentralized applications.',
      text: "Circle mints $750M USDC on Solana, marking the first injection of fresh USDC stablecoin liquidity on the network in 2026. This follows $56.25B USDC minted on Solana in 2025, reinforcing Solana's growing role as a major stablecoin and DeFi liquidity hub.",
      timestamp: '2026-01-02T17:00:00Z',
      price_on_fetch: 130.55,
      price_on_eval: 131.54,
      citations: [{ title: '2007386708032270424' }, { title: '2007383683783963093' }],
    },
    {
      project_id: 'ethereum',
      project_name: 'Ethereum',
      project_symbol: '$ETH',
      project_categories: [
        'smart-contract-platform',
        'layer-1',
        'ethereum-ecosystem',
        'proof-of-stake-pos',
        'world-liberty-financial-portfolio',
      ],
      project_description:
        'Ethereum is a global, open-source platform for decentralized applications.',
      text: 'Ethereum spot ETFs record $174M in net inflows on Jan. 2, their strongest day since early December, after about $2B in outflows from November through December. Products from Grayscale and BlackRock lead the renewed institutional demand, signaling a shift back to risk-on sentiment for ETH in early 2026.',
      timestamp: '2026-01-03T02:00:00Z',
      price_on_fetch: 3129.52,
      price_on_eval: 3114.78,
      citations: [{ title: '2007536719055167799' }, { title: '2007492243502858607' }],
    },
    {
      project_id: 'ethereum',
      project_name: 'Ethereum',
      project_symbol: '$ETH',
      project_categories: [
        'smart-contract-platform',
        'layer-1',
        'ethereum-ecosystem',
        'proof-of-stake-pos',
        'world-liberty-financial-portfolio',
      ],
      project_description:
        'Ethereum is a global, open-source platform for decentralized applications.',
      text: 'Ethereum set a new all-time high with about 2.2-2.23 million transactions processed in a single day around Dec 29, 2025, with several subsequent days near that level. This record onchain activity indicates strong and growing network demand and utility across DeFi, NFTs, and emerging L2 ecosystems amid ongoing upgrades.',
      timestamp: '2026-01-03T03:00:00Z',
      price_on_fetch: 3125.17,
      price_on_eval: 3110.91,
      citations: [{ title: '2007529962350207036' }, { title: '2007525811075665958' }],
    },
  ],
};
