name: on open PR to main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  # Only cancel in progress if is a PR
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

on:
  pull_request:
    branches:
      - main

jobs:
  run-tests:
    name: Run Tests
    uses: ./.github/workflows/run-tests.yaml
    secrets: inherit